// バレットのセリフ100件
const voiceLines = [
    // アバランチ・星の命系 (1-15)
    { id: 1, text: "星の命が削られてるんだぞ！", label: "星の命が削られてる！", audio: "audio/voice_001.mp3" },
    { id: 2, text: "アバランチの時間だぜ！", label: "アバランチの時間だぜ！", audio: "audio/voice_002.mp3" },
    { id: 3, text: "神羅の犬め！", label: "神羅の犬め！", audio: "audio/voice_003.mp3" },
    { id: 4, text: "俺たちの乗る列車は、途中下車はできねえぜ！", label: "途中下車はできねえぜ！", audio: "audio/voice_004.mp3" },
    { id: 5, text: "星を救うんだ！それ以外に何がある！", label: "星を救うんだ！", audio: "audio/voice_005.mp3" },
    { id: 6, text: "どいつもこいつも、神羅に騙されやがって！", label: "神羅に騙されやがって！", audio: "audio/voice_006.mp3" },
    { id: 7, text: "魔晄炉をぶっ壊す！それが俺たちのやり方だ！", label: "魔晄炉をぶっ壊す！", audio: "audio/voice_007.mp3" },
    { id: 8, text: "星が悲鳴を上げてるんだよ！聞こえねえのか！", label: "星が悲鳴を上げてる！", audio: "audio/voice_008.mp3" },
    { id: 9, text: "カネのために星を売る奴らは許さねえ！", label: "星を売る奴らは許さねえ！", audio: "audio/voice_009.mp3" },
    { id: 10, text: "勝負どころだ！気を引き締めろ！", label: "勝負どころだ！", audio: "audio/voice_010.mp3" },
    { id: 11, text: "星をすする寄生虫どもが！", label: "寄生虫どもが！", audio: "audio/voice_011.mp3" },
    { id: 12, text: "ミッドガルは腐りきってやがる。", label: "ミッドガルは腐ってる", audio: "audio/voice_012.mp3" },
    { id: 13, text: "プレジデント神羅……絶対にぶっ倒してやる！", label: "プレジデント神羅！", audio: "audio/voice_013.mp3" },
    { id: 14, text: "地下組織アバランチ、参上！", label: "アバランチ、参上！", audio: "audio/voice_014.mp3" },
    { id: 15, text: "七番街スラムの意地を見せてやる！", label: "七番街スラムの意地", audio: "audio/voice_015.mp3" },

    // 感情爆発・怒り系 (16-30)
    { id: 16, text: "へっ！ ざまあみやがれ！", label: "ざまあみやがれ！", audio: "audio/voice_016.mp3" },
    { id: 17, text: "アンタ、何様だ！", label: "アンタ、何様だ！", audio: "audio/voice_017.mp3" },
    { id: 18, text: "クソッ！クソッ！クソッ！", label: "クソッ！クソッ！クソッ！", audio: "audio/voice_018.mp3" },
    { id: 19, text: "オレの怒りが爆発するぜ！", label: "オレの怒りが爆発するぜ！", audio: "audio/voice_019.mp3" },
    { id: 20, text: "なんだと、コラァ！", label: "なんだと、コラァ！", audio: "audio/voice_020.mp3" },
    { id: 21, text: "ふざけんな！", label: "ふざけんな！", audio: "audio/voice_021.mp3" },
    { id: 22, text: "ぶっ飛ばしてやる！", label: "ぶっ飛ばしてやる！", audio: "audio/voice_022.mp3" },
    { id: 23, text: "おらおらおらぁ！", label: "おらおらおらぁ！", audio: "audio/voice_023.mp3" },
    { id: 24, text: "いい加減にしろよ、テメェら！", label: "いい加減にしろよ！", audio: "audio/voice_024.mp3" },
    { id: 25, text: "叩き潰してやるぜ！", label: "叩き潰してやるぜ！", audio: "audio/voice_025.mp3" },
    { id: 26, text: "舐めるんじゃねえ！", label: "舐めるんじゃねえ！", audio: "audio/voice_026.mp3" },
    { id: 27, text: "地獄へ落ちな！", label: "地獄へ落ちな！", audio: "audio/voice_027.mp3" },
    { id: 28, text: "てめぇの血は何色だ！", label: "てめぇの血は何色だ！", audio: "audio/voice_028.mp3" },
    { id: 29, text: "もう我慢できねえ！", label: "もう我慢できねえ！", audio: "audio/voice_029.mp3" },
    { id: 30, text: "ハチの巣にしてやる！", label: "ハチの巣にしてやる！", audio: "audio/voice_030.mp3" },

    // 仲間への呼びかけ・会話 (31-45)
    { id: 31, text: "行くぜ、相棒！", label: "行くぜ、相棒！", audio: "audio/voice_031.mp3" },
    { id: 32, text: "おい、クラウド！", label: "おい、クラウド！", audio: "audio/voice_032.mp3" },
    { id: 33, text: "ティファ！無事か！", label: "ティファ！無事か！", audio: "audio/voice_033.mp3" },
    { id: 34, text: "しょうがねえな、付き合ってやるよ。", label: "付き合ってやるよ", audio: "audio/voice_034.mp3" },
    { id: 35, text: "頼んだぜ、リーダー！", label: "頼んだぜ、リーダー！", audio: "audio/voice_035.mp3" },
    { id: 36, text: "ビッグス、ウェッジ、ジェシー……。", label: "仲間の名前", audio: "audio/voice_036.mp3" },
    { id: 37, text: "泣かせるじゃねえか。", label: "泣かせるじゃねえか", audio: "audio/voice_037.mp3" },
    { id: 38, text: "エアリス、大丈夫か？", label: "エアリス、大丈夫か？", audio: "audio/voice_038.mp3" },
    { id: 39, text: "レッドサーティーン、尻尾焦がすなよ！", label: "レッドサーティーン！", audio: "audio/voice_039.mp3" },
    { id: 40, text: "ユフィ、俺のギルに手ェ出すなよ！", label: "ユフィ、ギルに手ェ出すな！", audio: "audio/voice_040.mp3" },
    { id: 41, text: "シド、飛空艇の調子はどうだ？", label: "シド、飛空艇は？", audio: "audio/voice_041.mp3" },
    { id: 42, text: "ヴィンセント、たまには喋れよ。", label: "ヴィンセント、喋れよ", audio: "audio/voice_042.mp3" },
    { id: 43, text: "ケット・シー、占ってくれや。", label: "ケット・シー、占え", audio: "audio/voice_043.mp3" },
    { id: 44, text: "お前ら、死ぬなよ！", label: "お前ら、死ぬなよ！", audio: "audio/voice_044.mp3" },
    { id: 45, text: "俺たちが世界を救うんだ！", label: "俺たちが世界を救う！", audio: "audio/voice_045.mp3" },
    
    // マリン・ダイン・過去関連 (46-55)
    { id: 46, text: "マリン……パパは必ず帰ってくるからな。", label: "マリン……", audio: "audio/voice_046.mp3" },
    { id: 47, text: "ダイン……なんでこうなっちまったんだ。", label: "ダイン……", audio: "audio/voice_047.mp3" },
    { id: 48, text: "オレにはまだ、やらなきゃならねえ事がある！", label: "やらなきゃならねえ事", audio: "audio/voice_048.mp3" },
    { id: 49, text: "コレルのみんな……。", label: "コレルのみんな……", audio: "audio/voice_049.mp3" },
    { id: 50, text: "この右腕の痛みは、忘れねえ。", label: "右腕の痛み", audio: "audio/voice_050.mp3" },
    { id: 51, text: "マリンが待ってるんだ、死ねねえよ。", label: "マリンが待ってる", audio: "audio/voice_051.mp3" },
    { id: 52, text: "過去は変えられねえ、だが未来は……！", label: "未来は……！", audio: "audio/voice_052.mp3" },
    { id: 53, text: "エレノア……。", label: "エレノア……", audio: "audio/voice_053.mp3" },
    { id: 54, text: "オレの罪は、星を救って償う。", label: "オレの罪は償う", audio: "audio/voice_054.mp3" },
    { id: 55, text: "パパ、頑張るからな！", label: "パパ、頑張るからな！", audio: "audio/voice_055.mp3" },

    // 戦闘・リミットブレイク (56-70)
    { id: 56, text: "限界突破だ！ アンガーマックス！", label: "アンガーマックス！", audio: "audio/voice_056.mp3" },
    { id: 57, text: "ヘビーショット！", label: "ヘビーショット！", audio: "audio/voice_057.mp3" },
    { id: 58, text: "マインドブレイク！", label: "マインドブレイク！", audio: "audio/voice_058.mp3" },
    { id: 59, text: "グレネードボム！", label: "グレネードボム！", audio: "audio/voice_059.mp3" },
    { id: 60, text: "サテライトビーム！", label: "サテライトビーム！", audio: "audio/voice_060.mp3" },
    { id: 61, text: "カタストロフィ！", label: "カタストロフィ！", audio: "audio/voice_061.mp3" },
    { id: 62, text: "もらったァ！", label: "もらったァ！", audio: "audio/voice_062.mp3" },
    { id: 63, text: "そこだ！", label: "そこだ！", audio: "audio/voice_063.mp3" },
    { id: 64, text: "逃がさねえぜ！", label: "逃がさねえぜ！", audio: "audio/voice_064.mp3" },
    { id: 65, text: "まだまだぁ！", label: "まだまだぁ！", audio: "audio/voice_065.mp3" },
    { id: 66, text: "こんなモンかよ！", label: "こんなモンかよ！", audio: "audio/voice_066.mp3" },
    { id: 67, text: "回復してくれ！", label: "回復してくれ！", audio: "audio/voice_067.mp3" },
    { id: 68, text: "魔法をぶち込め！", label: "魔法をぶち込め！", audio: "audio/voice_068.mp3" },
    { id: 69, text: "俺に任せな！", label: "俺に任せな！", audio: "audio/voice_069.mp3" },
    { id: 70, text: "覚悟しな！", label: "覚悟しな！", audio: "audio/voice_070.mp3" },

    // コミカル・日常・その他 (71-85)
    { id: 71, text: "チョコボ、チョコボ、チョコボ〜", label: "チョコボの歌", audio: "audio/voice_071.mp3" },
    { id: 72, text: "お宝の匂いがプンプンするぜ！", label: "お宝の匂いがするぜ！", audio: "audio/voice_072.mp3" },
    { id: 73, text: "腹減ったな……。", label: "腹減ったな……", audio: "audio/voice_073.mp3" },
    { id: 74, text: "高いところは苦手なんだよ！", label: "高いところは苦手", audio: "audio/voice_074.mp3" },
    { id: 75, text: "階段キツイぜ……。", label: "階段キツイぜ……", audio: "audio/voice_075.mp3" },
    { id: 76, text: "セーラー服なんて着れるか！", label: "セーラー服なんて！", audio: "audio/voice_076.mp3" },
    { id: 77, text: "神羅ビル、長すぎだろ！", label: "神羅ビル、長すぎ！", audio: "audio/voice_077.mp3" },
    { id: 78, text: "ゴールドソーサー、最高だぜ！", label: "ゴールドソーサー最高！", audio: "audio/voice_078.mp3" },
    { id: 79, text: "コンドルフォートを防衛するぞ！", label: "コンドルフォート防衛！", audio: "audio/voice_079.mp3" },
    { id: 80, text: "スノボでもやるか？", label: "スノボでもやるか？", audio: "audio/voice_080.mp3" },
    { id: 81, text: "温泉に入いてえな。", label: "温泉に入いてえな", audio: "audio/voice_081.mp3" },
    { id: 82, text: "うおおおおっ！寒い寒い寒い！", label: "寒い寒い寒い！", audio: "audio/voice_082.mp3" },
    { id: 83, text: "俺の右腕、手入れが必要だな。", label: "右腕の手入れ", audio: "audio/voice_083.mp3" },
    { id: 84, text: "マテリア、ちゃんとセットしたか？", label: "マテリアセットしたか？", audio: "audio/voice_084.mp3" },
    { id: 85, text: "セーブポイントだ、休もうぜ。", label: "セーブポイントだ", audio: "audio/voice_085.mp3" },

    // 名言・決め台詞 (86-100)
    { id: 86, text: "俺はアバランチのリーダー、バレットだ！", label: "アバランチのリーダー", audio: "audio/voice_086.mp3" },
    { id: 87, text: "金で買えないモノもあるんだぜ。", label: "金で買えないモノ", audio: "audio/voice_087.mp3" },
    { id: 88, text: "後悔は死んでからするんだな！", label: "後悔は死んでから", audio: "audio/voice_088.mp3" },
    { id: 89, text: "男なら、背中で語れってんだ！", label: "男なら、背中で語れ", audio: "audio/voice_089.mp3" },
    { id: 90, text: "星の叫びが聞こえるか？", label: "星の叫びが聞こえるか？", audio: "audio/voice_090.mp3" },
    { id: 91, text: "オレの銃弾は、星の怒りだ！", label: "オレの銃弾は星の怒り", audio: "audio/voice_091.mp3" },
    { id: 92, text: "迷ったら、撃つ！ それだけだ！", label: "迷ったら、撃つ！", audio: "audio/voice_092.mp3" },
    { id: 93, text: "約束は守る。それがオレの流儀だ。", label: "約束は守る", audio: "audio/voice_093.mp3" },
    { id: 94, text: "仲間を見捨てるような奴は、オレが許さねえ！", label: "仲間は見捨てねえ", audio: "audio/voice_094.mp3" },
    { id: 95, text: "この腕で、全てを撃ち抜いてやる！", label: "全てを撃ち抜いてやる！", audio: "audio/voice_095.mp3" },
    { id: 96, text: "絶望の底から、這い上がってやるぜ。", label: "這い上がってやるぜ", audio: "audio/voice_096.mp3" },
    { id: 97, text: "神羅の野望、ここで打ち砕く！", label: "神羅の野望を砕く！", audio: "audio/voice_097.mp3" },
    { id: 98, text: "明日のために、今日を戦うんだ！", label: "明日のために戦う！", audio: "audio/voice_098.mp3" },
    { id: 99, text: "オレたちの物語は、ここからだ！", label: "オレたちの物語！", audio: "audio/voice_099.mp3" },
    { id: 100, text: "星よ、俺たちに力を貸してくれ！", label: "星よ、力を貸してくれ！", audio: "audio/voice_100.mp3" }
];

// --- アイコン画像の設定 ---
// ここに表示したい画像のURL（またはパス）を配列で設定します。
const iconImages = [
    "sprite/bullt01.jpg",
    "sprite/bullt02.jpg",
    "sprite/bullt03.jpg"
];
